# Generated by Django 6.0.1 on 2026-09-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doctor_name', models.CharField(max_length=200)),
                ('consultation_type', models.CharField(choices=[('In-Person', 'In-Person'), ('Online', 'Online')], default='In-Person', max_length=20)),
                ('appointment_date', models.CharField(max_length=50)),
                ('appointment_time', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Morning', 'Morning'), ('Midday', 'Midday'), ('Evening', 'Evening'), ('Bedtime', 'Bedtime')], default='Morning', max_length=20)),
                ('time_str', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=300)),
                ('icon_symbol', models.CharField(default='📌', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('player_name', models.CharField(default='Senior Player', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='Patient', max_length=200)),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Elderly Member', max_length=200)),
                ('age', models.IntegerField(default=70)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('medications_summary', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('photo_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Work', 'Work'), ('Shopping', 'Shopping'), ('Personal', 'Personal'), ('Health', 'Health')], default='Personal', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
