# Generated by Django 6.0.1 on 2026-10-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('senior', 'Senior Citizen'), ('doctor', 'Doctor')], default='senior', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('specialty', models.CharField(blank=True, default='General Physician', max_length=150, null=True)),
                ('hospital', models.CharField(blank=True, default='SageCare Medical Center', max_length=200, null=True)),
                ('license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, default=70, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('photo_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='call_room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescribed_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('In-Person', 'In-Person'), ('Online', 'Online')], default='Online', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='portal.useraccount'),
        ),
    ]
